- name: Deploy MAC Desktop with Ansible
  hosts: desktop

  tasks:
    - homebrew:
      name: "{{ packages }}"
      vars:
        packages:
          # - heroku/brew/heroku
          # - parity
          - azure-cli
          - bash-completion
          - caskroom/cask
          - caskroom/fonts
          - ccze
          - coreutils
          - curl
          - derailed/k9s/k9s
          - docker
          - font-hack-nerd-font
          - gcc
          - git
          - git-flow
          - git-ftp
          - git-lfs
          - go
          - google-chrome
          - gpg-suite
          - htop
          - hub
          - ibmcloud
          - imagemagick
          - iterm2
          - kubectl
          - kubernetes-helm
          - libmagic
          - libyaml
          - minikube
          - node
          - openssl
          - powerlevel9k
          - rcm
          - readline
          - reattach-to-user-namespace
          - sambadevi/powerlevel9k
          - skype
          - slack
          - sublime-text
          - terraform
          - the_silver_searcher
          - tmux
          - universal-ctags
          - vagrant
          - vagrant-manager
          - vim
          - virtualbox
          - watch
          - watchman
          - xz
          - yarn
          - zsh
      state: present