- name: Deploy MAC Desktop with Ansible
  hosts: desktop
  become: false
  tasks:
      - name: "Install Homebrew Packages"
        homebrew:
          name: "{{ packages }}"
          vars:
            packages:
              # - 'heroku/brew/heroku'
              # - 'parity'
              - 'autoconf'
              - 'azure-cli'
              - 'bash-completion'
              - 'bash-completion'
              - 'boot2docker'
              - 'caskroom/cask'
              - 'caskroom/fonts'
              - 'ccze'
              - 'consul'
              - 'coreutils'
              - 'curl'
              - 'derailed/k9s/k9s'
              - 'docker-compose'
              - 'docker-machine'
              - 'doxygen'
              - 'gcc'
              - 'git'
              - 'git-flow'
              - 'git-ftp'
              - 'git-lfs'
              - 'go'
              - 'htop'
              - 'hub'
              - 'ibmcloud'
              - 'imagemagick'
              - 'jq'
              - 'kubectl'
              - 'kubernetes-helm'
              - 'libmagic'
              - 'libyaml'
              - 'nmap'
              - 'node'
              - 'nomad'
              - 'openssl'
              - 'packer'
              - 'powerlevel9k'
              - 'pyenv'
              - 'python'
              - 'rancher-compose'
              - 'rbenv'
              - 'rcm'
              - 'readline'
              - 'reattach-to-user-namespace'
              - 'ruby-build'
              - 'sambadevi/powerlevel9k'
              - 'ssh-copy-id'
              - 'sublime-text'
              - 'terraform'
              - 'terraform-inventory'
              - 'terraform-provisioner-ansible'
              - 'the_silver_searcher'
              - 'tmux'
              - 'tree'
              - 'universal-ctags'
              - 'vault'
              - 'vim'
              - 'watch'
              - 'watchman'
              - 'wget'
              - 'xz'
              - 'yarn'
              - 'zsh'
              - 'zsh-syntax-highlighting'
          state: present
          update_homebrew: yes
          upgrade_all: yes
      
      - name: "Install Homebrew Cask Packages"
        homebrew_cask:
          name: "{{ packages }}"
          vars:
            packages:
              - 'atom'
              - 'docker'
              - 'dropbox'
              - 'firefox'
              - 'font-hack-nerd-font'
              - 'google-chrome'
              - 'google-drive'
              - 'google-hangouts'
              - 'gpg-suite'
              - 'iterm2'
              - 'keepassx'
              - 'lastpass'
              - 'macvim'
              - 'minikube'
              - 'royal-tsx'
              - 'skype'
              - 'slack'
              - 'sling'
              - 'spotify'
              - 'sublime-text'
              - 'vagrant'
              - 'vagrant-manager'
              - 'virtualbox'
              - 'virtualbox-extension-pack'
              - 'visual-studio-code'
          state: present
          update_homebrew: yes
          upgrade_all: yes